### ISSUE TITLE
Add troubleshooting steps to all network response codes

### ISSUE THREAD

**Issue by SimiHunjan** [hiero-ledger/hiero-docs#118]
### Problem

It would be helpful to developers to provide a set of instructions on how to troubleshoot the network response code.

### Solution

Add trouble shooting steps the network response codes.

```[tasklist]
### Tasks
- [ ] Document all the response codes provided from the network
- [ ] Desgin a sectionin docs that will have the corresponding pages to troubleshoot each error code
- [ ] Work with SMEs to provide the steps to resolve each error code
- [ ] Review the content
- [ ] Publish the content
- [ ] Establish process to add new error codes
```

**Comment by SimiHunjan** [comment]
Here is an example of what we could have: 

https://kinsta.com/blog/http-error-503/#:~:text=The%20HTTP%20503%20Service%20Unavailable%20error%20means%20that%20a%20website,which%20requires%20a%20deeper%20analysis.&text=Running%20into%20errors%20on%20your%20site%20can%20be%20intimidating
