### ISSUE TITLE
Add HIP-657: Mutable metadata fields for dynamic NFTs

### ISSUE THREAD

**Issue by theekrystallee** [hiero-ledger/hiero-docs#303]
### Problem

Docs/tutorial for HIP-657 missing

### Solution

Add tutorial to docs site 

https://hips.hedera.com/hip/hip-657

```[tasklist]
### Tasks
- [x] Under the token service SDK section, add "Update token metadata" page and the details for this new transaction
- [x] Under "Create a token" add information about the metadata key
- [x] Under "Update a token" add information about the metadata key
- [x] Publish release v0.49 goes live on testnet
```

**Comment by theekrystallee** [comment]
Resolved in [5c87ca5](https://github.com/hashgraph/hedera-docs/commit/5c87ca58987f7fd0af56e7737fc661bb69543e53)
