### ISSUE TITLE
Add a Glossary section

### ISSUE THREAD

**Issue by Nana-EC** [hiero-ledger/hiero-docs#337]
### Problem

The Hedera ecosystem has a lot of terms that may not be familiar to all.
Some of these additionally mean different things in different products e.g. address book (platform vs mirror node), synthetic transactions (platform vs service)

### Solution

We should add a glossary section to the docs website with appropriate section to allow for easy searching and reading of terms.

Additionally terms may have tags to notify the product, service they refer to. There may be other tags/criteria to consider

Suggestions (to be reviewed for UX considerations 😄  )
- [x] Add a Glossary page with an overview of Glossary intentions
- [x] Add sections for 0-9,A-Z that list terms based on the first letter
- [ ] Add sections that presents term via their category e.g. platform/services or Smart Contracts/Tokens
- [x] Support terms page displaying additional content like a link to a blog or a video to further explain 
- [ ] ...

**Comment by SimiHunjan** [comment]
Item 1,2 and 4 are complete. Gitbook does not have a feature that will easily allow us to label by category. Closing as complete.
