### ISSUE TITLE
Update smart contract section

### ISSUE THREAD

**Issue by SimiHunjan** [hiero-ledger/hiero-docs#351]
The smart contract section under core concepts needs to be redefined.

- [x] https://github.com/hashgraph/hedera-docs/issues/426
- [x] https://github.com/hashgraph/hedera-docs/issues/90
- [x] https://github.com/hashgraph/hedera-docs/issues/433
- [x] https://github.com/hashgraph/hedera-docs/issues/434
- [x] Compile smart contracts

```[tasklist]
### Tasks
- [x] https://github.com/hashgraph/hedera-docs/issues/426
- [x] https://github.com/hashgraph/hedera-docs/issues/90
- [x] https://github.com/hashgraph/hedera-docs/issues/433
- [x] https://github.com/hashgraph/hedera-docs/issues/434
- [x] Compile smart contracts
- [ ] https://github.com/hashgraph/hedera-docs/issues/463
```
