### ISSUE TITLE
EVM Dcoumentation Enhancements

### ISSUE THREAD

**Issue by theekrystallee** [hiero-ledger/hiero-docs#399]
```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-docs/issues/807
- [ ] https://github.com/hashgraph/hedera-docs/issues/825
- [ ] https://github.com/hashgraph/hedera-docs/issues/401
- [ ] https://github.com/hashgraph/hedera-docs/issues/402
- [ ] https://github.com/hashgraph/hedera-docs/issues/403
- [ ] https://github.com/hashgraph/hedera-docs/issues/211
- [ ] https://github.com/hashgraph/hedera-docs/issues/396
- [ ] https://github.com/hashgraph/hedera-docs/issues/818
- [ ] https://github.com/hashgraph/hedera-docs/issues/400
- [ ] https://github.com/hashgraph/hedera-docs/issues/391
- [ ] https://github.com/hashgraph/hedera-docs/issues/404
- [ ] https://github.com/hashgraph/hedera-docs/issues/390
- [ ] https://github.com/hashgraph/hedera-docs/issues/219
- [ ] https://github.com/hashgraph/hedera-docs/issues/214
- [ ] https://github.com/hashgraph/hedera-docs/issues/338
- [ ] https://github.com/hashgraph/hedera-docs/issues/809
```
