### ISSUE TITLE
Deprecate Hethers

### ISSUE THREAD

**Issue by theekrystallee** [hiero-ledger/hiero-docs#404]
With the release of the Hedera JSON-RPC Relay, Hedera developers can use ethers.js. Hethers was a library that was developed prior to the availability of the relay. The plan is to deprecate hethers.js library in favor of using ethers.js which is very well known in the smart contract community. 
```[tasklist]
### Tasks
- [x] When the deprecation timeline is determined, update the relavent sections in docs
- [x] Identify the sections in docs where this callout/hint would need to be displayed
- [x] When the deprecation window has ended, remove the hethers.js section
```
