### ISSUE TITLE
Add HIPs to Documentation

### ISSUE THREAD

**Issue by theekrystallee** [hiero-ledger/hiero-docs#408]
```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-docs/issues/413
- [ ] https://github.com/hashgraph/hedera-docs/issues/412
- [ ] https://github.com/hashgraph/hedera-docs/issues/411
- [ ] https://github.com/hashgraph/hedera-docs/issues/410
- [ ] https://github.com/hashgraph/hedera-docs/issues/409
- [ ] https://github.com/hashgraph/hedera-docs/issues/303
```
