### ISSUE TITLE
Add HIP-540: Change or Remove Existing Keys From A Token

### ISSUE THREAD

**Issue by theekrystallee** [hiero-ledger/hiero-docs#410]
All entities across Hedera have opt-in administrative keys. Currently, the Consensus Service and File service allow these keys to be removed (making the entities immutable). However the Hedera Token Service does not provide such a feature consistently. We should enable existing administrative keys for tokens created with the Hedera Token Service to be able to sign an update transaction that changes or permanently removes any privileged key (Admin, Wipe, KYC, Freeze, Pause, Supply, Fee Schedule) from the entity.

HIP: https://hips.hedera.com/hip/hip-540
```[tasklist]
### Tasks
- [ ] Identify the areas in docs that would need to be updated
- [ ] Draft the content for the update
- [ ] Push the update when the feature lands on testnet
```

**Comment by theekrystallee** [comment]
Resolved in #636
