### ISSUE TITLE
Add HIP-646: Fungible Token Metadata Field

### ISSUE THREAD

**Issue by theekrystallee** [hiero-ledger/hiero-docs#413]
HIP-646 introduces new token metadata fields that is stored with the token object on the network. The docs will need to be updated with the new field that is released in the SDKs for the following transactions:

- [x] `TokenCreateTransaction`
- [x] `TokenUpdateTransaction`
- [x] `TokenInfoQuery`

HIP: https://hips.hedera.com/hip/hip-646

Hedera Services Release: TBD
```[tasklist]
### Tasks
- [x] Identify the sections in the docs site that are required to be updated
- [x] Draft the required content needed for the update
- [x] Publish release v0.48 goes live on testnet
```

**Comment by theekrystallee** [comment]
Resolved in [5c87ca5](https://github.com/hashgraph/hedera-docs/commit/5c87ca58987f7fd0af56e7737fc661bb69543e53)
