### ISSUE TITLE
Tutorial for Stablecoin Accelerator

### ISSUE THREAD

**Issue by theekrystallee** [hiero-ledger/hiero-docs#415]
Create a tutorial for the Stablecoin accelerator.  This issue depends on #416. 
```[tasklist]
### Tasks
- [x] Outline the sections required for the stablecoin tutorial
- [ ] Test the tutorial end to end
- [ ] SME to review and provide feedback on the tutorial
```

**Comment by theekrystallee** [comment]
Duplicate
