### ISSUE TITLE
Create dedicated docs for "Stablecoins on Hedera"

### ISSUE THREAD

**Issue by theekrystallee** [hiero-ledger/hiero-docs#416]
```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-docs/issues/422
- [ ] https://github.com/hashgraph/hedera-docs/issues/423
- [ ] https://github.com/hashgraph/hedera-docs/issues/425
- [ ] Get feedback from the SME's for stablecoin section
- [ ] Review and publish documentation
```

**Comment by theekrystallee** [comment]
Duplicate
