### ISSUE TITLE
Stablecoin Studio Documentation

### ISSUE THREAD

**Issue by theekrystallee** [hiero-ledger/hiero-docs#418]
This EPIC defines the list of tasks that need to be completed to add a stable coin section to the docs site.

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-docs/issues/422
- [ ] https://github.com/hashgraph/hedera-docs/issues/425
- [ ] https://github.com/hashgraph/hedera-docs/issues/423
- [ ] https://github.com/hashgraph/hedera-docs/issues/447
- [ ] https://github.com/hashgraph/hedera-docs/issues/445
- [ ] https://github.com/hashgraph/hedera-docs/issues/446
- [x] Add GitPod configuration file in Stablecoin Studio repo
- [x] Get feedback from the SME's for stablecoin section
- [x] Review and publish
```
