### ISSUE TITLE
docs: add hscs workshop

### ISSUE THREAD

**Issue by bguiz** [hiero-ledger/hiero-docs#429]
- https://github.com/hashgraph/hedera-docs/pull/417
- https://github.com/hashgraph/hedera-docs/pull/421

```[tasklist]
### Tasks
- [x] Run the workshop tutorial
- [x] Review and update to style guide
- [x] Provide tutorial feedback to author, if any
```
