### ISSUE TITLE
Update docs with how to use the Hedera faucet 

### ISSUE THREAD

**Issue by SimiHunjan** [hiero-ledger/hiero-docs#441]
### Problem

The Hedera faucet will be a way to anonymously get testnet hbar and create an account. Docs will need to be updated to capture this new flow.

### Solution

Add content for the Hedera faucet and complete the tasks listed in the task list section. 
```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-docs/issues/531
- [x] Update getting started with the Hedera faucet flow for anonymous account creation
- [x] Update "Testnet Accounts" under Networks > Testnets
```

**Comment by theekrystallee** [comment]
Resolved in [2db233a](https://github.com/hashgraph/hedera-docs/commit/2db233a973bb0ab4b407716db3e975f2a0803d4b)
