### ISSUE TITLE
Add Wallet Connect + Metamask Snap Information 

### ISSUE THREAD

**Issue by SimiHunjan** [hiero-ledger/hiero-docs#471]
### Problem

TBD

### Solution

TBD

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-docs/issues/513
- [x] Link Tuum's Hedera Wallet Snap documentation to docs.hedera.c
- [x] Create landing page
```

**Comment by theekrystallee** [comment]
MetaMask Hedera Wallet Snap documentation has been linked
