### ISSUE TITLE
Update tutorial with TokenAssociateTransaction and AccountAllowanceApproveTransaction functions

### ISSUE THREAD

**Issue by theekrystallee** [hiero-ledger/hiero-docs#474]
```[tasklist]
### Tasks
- [x] Update JavaScript code snippet
- [x] Update Java code snippet
- [x] Update Go code snippet
- [ ] #495
```

**Comment by theekrystallee** [comment]
Resolved in [b003712](https://github.com/hashgraph/hedera-docs/commit/b00371242243e23f2e4b9167bc1c5674cedd7ff6)
