### ISSUE TITLE
Test the Crowdin integration and workflow in a staging environment

### ISSUE THREAD

**Issue by SimiHunjan** [hiero-ledger/hiero-docs#497]
Crowdin is a cloud-based platform that helps businesses manage the localization (translation) of their software, websites, and other content. It allows teams to collaborate on translations, track progress, and ensure that their products are available in multiple languages.

We are looking to support three languages with this integration. DLT Science will be responsible for proof reading the transactions that are auto generated by Crowdin and respond to issues from developers in those supported languages.

We need a way to do end to end testing for this workflow.

**Tasks**

- [x] Create a Hedera docs staging environment @SimiHunjan 
- [x] The Hedera docs staging environment will be assigned to the staging branch in GitHub @SimiHunjan 
- [x] The staging branch will be linked to the Hedera Staging GitBook space @SimiHunjan 
- [ ] The Hedera Staging space will need to go through the steps of creating a collection as we expect to do with the production space
- [x] The GitBook staging site has its own URL we can view the implemented changes @SimiHunjan 
- [ ] Crowdin instance will need to point the Hedera docs repo and linked to the staging branch @swirlds-matt 
- [ ] The Crowding translations need to be written to the staging branch @swirlds-matt 
- [ ] Once the directories for each language are present, we need to submit a PR/chnage to staging and observe the translation process
- [ ] Crowdin also needs to be updated with the proof reader role add the individuals from DLT Science that will be responsible @swirlds-matt 
- [ ] We should schedule a meeting with DevRel/DLT Science/Docs to go through the end to end work flow @swirlds-matt 
- Push a new change to the staging branch
- Crowdin should pick up the change and do the translations
- DLT Science proof readers will read an approve
- The PR gets opened to the staging branch
- A PR is made from the staging branch to the master branch
- The PR is merged

Once we validate the end to end process, address open questions, and have assigned clear ownership for which teams owns what part of the process we can schedule the work to complete this on the production site.

**Comment by SimiHunjan** [comment]
Staging branch can be found here: https://github.com/hashgraph/hedera-docs/tree/staging

**Comment by SimiHunjan** [comment]
closing as not planned
