### ISSUE TITLE
"Coming from Ethereum?" doc to address IOActive report on confusing features

### ISSUE THREAD

**Issue by SimiHunjan** [hiero-ledger/hiero-docs#525]
### Problem

The IOActive reported that it was confusing for developers coming from Ethereum to understand Hedera features. A dedicated page that compares and contrasts the similarties and differences about Hedera features vs. Ethereum features may address this confusion.

### Solution

Create a dedicated page for Ethereum developers coming to Hedera to get started in understanding the similarities and differences between features.

```[tasklist]
### Tasks
- [ ] Research Ethereum to understand the feature landscape to identify the similarities and differences
- [ ] Design the page structure and add the content
- [ ] Work with the smart contract team SMEs to validate the content
- [ ] Interview a few smart contract developers who cam from Ethereum to Hedera
```

**Comment by Ferparishuertas** [comment]
Addressed here

https://docs.hedera.com/hedera/core-concepts/smart-contracts/understanding-hederas-evm-differences-and-compatibility
