### ISSUE TITLE
ETHDenver: Create developer survey + ETH hackathon starter pack

### ISSUE THREAD

**Issue by theekrystallee** [hiero-ledger/hiero-docs#537]
```[tasklist]
### Tasks
- [x] Create Notion doc to compile all survey efforts/questions
- [x] Vote and compile top voted into a new list
- [x] Review and approve final questions to be added to survey
- [ ] https://github.com/hashgraph/hedera-docs/issues/562
- [ ] https://github.com/hashgraph/hedera-docs/issues/554
```
