### ISSUE TITLE
Update: Contributing and Style Guide

### ISSUE THREAD

**Issue by theekrystallee** [hiero-ledger/hiero-docs#556]
```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-docs/issues/782
- [x] https://github.com/hashgraph/hedera-docs/issues/848
- [ ] https://github.com/hashgraph/hedera-docs/issues/559
- [ ] https://github.com/hashgraph/hedera-docs/issues/398
- [ ] https://github.com/hashgraph/hedera-docs/issues/830
```
