### ISSUE TITLE
Documentation: Create a `Localnet` section under "Networks"

### ISSUE THREAD

**Issue by theekrystallee** [hiero-ledger/hiero-docs#558]
Consider creating a `Localnet` section under [Networks](https://docs.hedera.com/hedera/networks). This new section could contain a series of subpages focused on development using local node as we do for testnet. 
```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-docs/issues/552
- [ ] https://github.com/hashgraph/hedera-docs/issues/593
- [x] Add multinode mode documentation
- [ ] https://github.com/hashgraph/hedera-docs/issues/602
- [ ] https://github.com/hashgraph/hedera-docs/issues/626
- [ ] https://github.com/hashgraph/hedera-docs/issues/638
```

**Comment by theekrystallee** [comment]
[Localnet docs are live](https://docs.hedera.com/hedera/networks/localnet). Resolved in [0184579](https://github.com/hashgraph/hedera-docs/commit/0184579bdfb7b115930a6dab2fb7b90e13e7bd6a)
