### ISSUE TITLE
Consolidate Account Creation Examples for Developer Clarity

### ISSUE THREAD

**Issue by theekrystallee** [hiero-ledger/hiero-docs#566]
## Background info
Multiple examples exist for creating an account & should probably be consolidated to prevent confusion in devs.

* This one: https://github.com/hashgraph/hedera-sdk-js/blob/develop/examples/create-account.js references `Wallet` and `LocalProvider`, and the state of these classes is unknown.

* The getting-started one : https://docs.hedera.com/hedera/getting-started/create-an-account#javascript-5 uses a client. 

* The hello world create and fund account: https://docs.hedera.com/hedera/tutorials/hello-world/create-fund-account essentially follows the same way getting-started does but is in a tutorial format.

I have seen developers over time reference all three examples, which could potentially cause confusion as to what the source of truth is. It is great to have multiple ways to do things; however, stating the pros and cons of each will be crucial in helping developers understand which approach to take.

## Suggested Action Items

- [ ] Determine the status of `Wallet` and `LocalProvider` classes. 
    - [ ] Are they still relevant?
    - [ ]  Does the efforts with WalletConnect make them obsolete?
- [ ] Determine how to consolidate or if all 3 want to be kept, than to discern the difference between them in a clear and concise manner that will help developers which path is the right for their use case.
- [ ] Identify responsible teams/team members to help in this initiative

**Comment by theekrystallee** [comment]
https://hips.hedera.com/hip/hip-583
