### ISSUE TITLE
Add a Partners section in Stablecoin Studio docs

### ISSUE THREAD

**Issue by theekrystallee** [hiero-ledger/hiero-docs#601]
We have some partners that support stablecoin studio such as Elliptic, it would make sense I think to add a section to the stablecoin studio docs (https://docs.hedera.com/hedera/open-source-solutions/stablecoin-studio/web-ui-application#start-the-web-ui) listing partners by category. Elliptic would be in a "Know your transaction" category. 

```[tasklist]
### Tasks
- [ ] Add a partners page and link to partner websites
- [ ] Add `Oracles`,`KYC`, and `Custody Providers` under custody providers
- [ ] Add DFNS under custody providers
```

**Comment by gregscullard** [comment]
Suggested description for DFNS

```DFNS: Web3 wallets as an api - One simple integration supercharges your platform with seedless wallets providing maximum security and freedom for crypto.```

And link to https://www.dfns.co

**Comment by gregscullard** [comment]
And for Elliptic (`Compliance Partners` Section in the doc)

About Elliptic

Elliptic powers the intelligence that helps crypto businesses, financial institutions, law enforcement, and regulators make faster, smarter, and safer decisions. As the pioneer of blockchain analytics and a leading authority in the industry, Elliptic assesses billions of dollars worth of crypto transactions activity everyday delivering detailed on-chain insight through our financial crime and compliance solutions.

Comprising next generation transaction screening, wallet screening, investigations, due diligence, and VASP screening solutions, our blockchain analytics platform enables issuers to implement robust anti-money laundering (AML) and Know Your Customer (KYC) compliance measures, ensuring that they can confidently navigate an increasingly complex cryptocurrency landscape.

https://www.elliptic.co/

**Comment by theekrystallee** [comment]
@gregscullard do you mean in addition to how they are listed on SS core concepts page? https://docs.hedera.com/hedera/open-source-solutions/stablecoin-studio/core-concepts#ecosystem-integrations
