### ISSUE TITLE
Address feedback from ETHDenver hackers

### ISSUE THREAD

**Issue by theekrystallee** [hiero-ledger/hiero-docs#616]
```[tasklist]
### Tasks
- [x] https://github.com/hashgraph/hedera-docs/issues/619
- [ ] https://github.com/hashgraph/hedera-docs/issues/620
- [ ] https://github.com/hashgraph/hedera-docs/issues/621
```
