### ISSUE TITLE
Docs update: v0.48 release features

### ISSUE THREAD

**Issue by theekrystallee** [hiero-ledger/hiero-docs#622]
```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-docs/issues/303
- [ ] https://github.com/hashgraph/hedera-docs/issues/413
- [ ] https://github.com/hashgraph/hedera-docs/issues/529
- [x] docs are ready to go live
- [x] Add performance results graphics
- [ ] https://github.com/hashgraph/hedera-docs/issues/569
- [ ] https://github.com/hashgraph/hedera-docs/issues/641
```
