### ISSUE TITLE
Docs update: v0.49 release features

### ISSUE THREAD

**Issue by theekrystallee** [hiero-ledger/hiero-docs#623]
```[tasklist]
### Tasks
- [x] Add 0.49 release notes to release notes sec
- [ ] https://github.com/hashgraph/hedera-docs/issues/671
- [ ] https://github.com/hashgraph/hedera-docs/issues/410
- [ ] https://github.com/hashgraph/hedera-docs/issues/303
- [ ] https://github.com/hashgraph/hedera-docs/issues/413
- [ ] https://github.com/hashgraph/hedera-docs/issues/529
- [ ] https://github.com/hashgraph/hedera-docs/issues/569
- [x] Add 0.49.1 release notes to release notes sec
- [ ] https://github.com/hashgraph/hedera-docs/issues/650
- [ ] https://github.com/hashgraph/hedera-docs/issues/655
- [ ] https://github.com/hashgraph/hedera-docs/issues/662
```
