### ISSUE TITLE
getting started redesign planning

### ISSUE THREAD

**Issue by theekrystallee** [hiero-ledger/hiero-docs#628]
**Related Issues**
```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-docs/issues/625
- [ ] https://github.com/hashgraph/hedera-docs/issues/616
- [ ] https://github.com/hashgraph/hedera-docs/issues/264
- [ ] https://github.com/hashgraph/hedera-docs/issues/629
- [ ] https://github.com/hashgraph/hedera-docs/issues/680
```
