### ISSUE TITLE
docs: Create HashioDAO documentation

### ISSUE THREAD

**Issue by theekrystallee** [hiero-ledger/hiero-docs#631]
https://github.com/hashgraph/hedera-accelerator-defi-dex-ui
```[tasklist]
### Tasks
- [x] Introduction to DAOs and HashDAO
- [x] Tutorial on DAO creation
- [x] Add HashioDAO terminology to glossary
```

**Comment by theekrystallee** [comment]
Added and resolved in [14b0034](https://github.com/hashgraph/hedera-docs/commit/14b00343fca57d886e29a18fe85e7ed0c46e5368)
