### ISSUE TITLE
docs survey feedback issues

### ISSUE THREAD

**Issue by theekrystallee** [hiero-ledger/hiero-docs#640]
```[tasklist]
### Tasks
- [ ] Enhancing the overview and fundamental concepts sections to include all relevant concepts and parameters.
- [ ] Providing comprehensive explanations and examples for semantically rich features unique to Hedera.
- [ ] Clarifying the impact of Ethereum equivalence on various aspects of the platform.
- [ ] Improving documentation on API interactions, potential problems, and parameter usage.
- [ ] Expanding API descriptions to provide more detailed explanations of parameters and their impacts.
```
