### ISSUE TITLE
docs: implement getting started redesign

### ISSUE THREAD

**Issue by theekrystallee** [hiero-ledger/hiero-docs#643]
```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-docs/issues/678
- [ ] https://github.com/hashgraph/hedera-docs/issues/695
- [ ] https://github.com/hashgraph/hedera-docs/issues/689
- [ ] https://github.com/hashgraph/hedera-docs/issues/677
- [ ] https://github.com/hashgraph/hedera-docs/issues/676
- [ ] https://github.com/hashgraph/hedera-docs/issues/674
```
