### ISSUE TITLE
Docs update: v0.50 release features

### ISSUE THREAD

**Issue by theekrystallee** [hiero-ledger/hiero-docs#652]
```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-docs/issues/611
- [ ] https://github.com/hashgraph/hedera-docs/issues/635
- [x] Add v0.50.0 release notes to doc
- [ ] https://github.com/hashgraph/hedera-docs/issues/409
- [ ] Add v0.50.1 release notes
```
