### ISSUE TITLE
Getting Started Series Redesign

### ISSUE THREAD

**Issue by theekrystallee** [hiero-ledger/hiero-docs#687]
```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-docs/issues/685
- [ ] https://github.com/hashgraph/hedera-docs/issues/682
- [ ] add end-to-end  code for each SDK language to repo
```

**Comment by theekrystallee** [comment]
duplicate of #643
