### ISSUE TITLE
Add HIP-904 docs: Frictionless Airdrop

### ISSUE THREAD

**Issue by theekrystallee** [hiero-ledger/hiero-docs#698]
HIP-904 brings frictionless airdrops with senders able to create token associations for receivers at transfer. It eliminates the need for pre-association. It also supports pending token transfers for accounts that do not wish to receive unsolicited tokens, allowing receivers to claim or reject these airdrops. This will reduce user friction, enhance token association workflows, and prevent spam by making the user's experience as good as it can be with fungible and non-fungible tokens.

https://hips.hedera.com/hip/hip-904

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-docs/issues/701
- [ ] https://github.com/hashgraph/hedera-docs/issues/702
- [ ] https://github.com/hashgraph/hedera-docs/issues/703
```
