### ISSUE TITLE
Update HAPI section to use the auto generated documentation for protobuf APIs

### ISSUE THREAD

**Issue by SimiHunjan** [hiero-ledger/hiero-docs#72]
### Problem

This section is manually update every release and has the possibility to be out of date. GitHub creates automated documentation each time the protobufs are updated that should stay up to date. 

### Solution

Update the HAPI section with the link to the auto-generated protobuf API docs https://hashgraph.github.io/hedera-protobufs/.

```[tasklist]
### Tasks
- [ ] Design the Hedera protobufs landing page
- [ ] Source the content required for the landing page and link the auto generated protobuf documentation
- [ ] SMEs to review the documentation
```

**Comment by SimiHunjan** [comment]
This might mean we change the pages in the HAPI section to hyperlinks to the auto generated page
