### ISSUE TITLE
docs update: v0.52 release features

### ISSUE THREAD

**Issue by theekrystallee** [hiero-ledger/hiero-docs#733]
```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-docs/issues/702
- [ ] https://github.com/hashgraph/hedera-docs/issues/735
- [ ] https://github.com/hashgraph/hedera-docs/issues/734
```
