### ISSUE TITLE
docs update: v0.54 release features

### ISSUE THREAD

**Issue by theekrystallee** [hiero-ledger/hiero-docs#740]
```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-docs/issues/785
- [ ] https://github.com/hashgraph/hedera-docs/issues/710
- [ ] https://github.com/hashgraph/hedera-docs/issues/703
```
