### ISSUE TITLE
Restructure style guide page and add detailed style guide guidelines.

### ISSUE THREAD

**Issue by deshmukhpranali** [hiero-ledger/hiero-docs#830]
```[tasklist]
### Tasks
- [x] Restructure the 'Contributing and Style Guide' page into pages and subpages
- [x] Create 'Contribution Guidelines' page under the 'Contributing and Style Guide' page.
- [x] Create 'Style Guide' page under the 'Contributing and Style Guide' page.
- [x] Under the 'Contribution Guidelines' create pages for 'Creating Issues', 'Creating Pull Requests', 'Hedera Improvement Proposal (HIP)' and 'Submit Demo Applications'.
- [x] Under the 'Style Guide' create pages for 'Understanding different types of documentation', 'Use of HBAR', 'Use of web2 and web3', 'Language and grammar', 'Formatting' and 'Punctuation'.
```

**Comment by deshmukhpranali** [comment]
Changes reviewed and feedback implemented
