### ISSUE TITLE
getting started updates with feedback

### ISSUE THREAD

**Issue by theekrystallee** [hiero-ledger/hiero-docs#867]
```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-docs/issues/866
- [ ] https://github.com/hedera-dev/hello-future-world-js/pull/23
- [ ] https://github.com/hedera-dev/hello-future-world-java/pull/12
- [ ] https://github.com/hedera-dev/hello-future-world-go/pull/8
```
